learning_log/accounts/urls.py
from django.urls import path,include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('',include('django.contrib.auth.urls')), #include('django.contrib.auth.urls')用于引入 Django 自带的身份认证系统中的 URL 配置
    path('register/', views.register, name='register'),
]

learning_log/learning_logs/urls.py
from django.urls import path
from . import views  #句点让 Python 从当前 urls.py 模块所在的文件夹中导入 views

app_name = 'learning_logs'
urlpatterns = [         
    # 主页
    path('', views.index, name='index'),
    path('topics/',views.topics,name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>',views.new_entry,name='new_entry'),
    path('edit_entry/<int:entry_id>',views.edit_entry,name='edit_entry'),
]   
#     让 Django 查找在基础 URL 后紧跟单词 topics 的
# URL，第二部分（/<int:topic_id>/）与在两个斜杠之间的整
# 数匹配，并将这个整数赋给实参 topic_id。
    
#urlpatterns 是一个列表，包含可在应用程序 learning_logs中请求的网页

learning_log/ll_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('', include('learning_logs.urls')),
]

learning_log/accounts/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Topic(models.Model):              # 一个继承了model的类
    text = models.CharField(max_length=200)     # CharField是字符串字段   max_length=200代表预留了多少空间(即200个字符)
    #需要存储少量文本（如名称、标题或城市）时,可使用CharField。
    date_added = models.DateTimeField(auto_now_add=True)
    #DateTimeField 是一个记录时间的数据  auto_now_add=True 表示自动设置当前时间
    
    owner = models.ForeignKey(User, on_delete=models.CASCADE)#它会建立到模型 User 的外键关系。当用户被删除时，所有与之相关联的主题也会被删除。

    def __str__(self):   #如果模型有__str__()方法,那么每次需要生成表示模型实例的输出时,都会调用这个方法
        return self.text
    
class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)#实参 on_delete=models.CASCADE 让Django 在删除主题的同时删除所有与之相关联的条目，这称为级联删除
    text = models.TextField()   # TextField实例 长度不受限
    date_added = models.DateTimeField(auto_now_add=True)#让我们能够按创建顺序呈现条目，并在每个条目旁边放置时间戳。

    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
        return f"{self.text[:50]}..."

learning_log/learning_logs/forms.py
from django import forms
from .models import Topic
from .models import Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}
    
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}#让 Django 使用宽度为 80 列

learning_log/accounts/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    if request.method !='POST':
        form = UserCreationForm()# 显示空的注册表单
    else :
        form = UserCreationForm(data = request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)# 让用户自动登录，再重定向到主页
            return redirect('learning_logs:index')
    context = {'form':form}# 显示空表单或指出表单无效
    return render(request, 'registration/register.html', context)
    

learning_log/learning_logs/views.py
from django.shortcuts import render,redirect
from .models import Topic,Entry
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .forms import TopicForm,EntryForm

# Create your views here.
def index(request):
    return render(request,'learning_logs/index.html')

@login_required #login_required() 的代码检查用户是否已登录。仅当用户已登录时，Django 才运行 topics() 的代码。否则重定向到登陆页面
def topics(request):
    # topics = Topic.objects.order_by('date_added')
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')#让 Django 只从数据库中获取 owner 属性为当前用户的 Topic 对象。
    
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request,topic_id):
    topic = Topic.objects.get(id=topic_id)

    if topic.owner != request.user:
        raise Http404
    
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic,'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()          #如果为GET 请求，创建一个新表单
    else:
        form = TopicForm(data = request.POST)
        if form.is_valid():#方法 is_valid() 核实用户填写了所有必不可少的字段
            
            new_topic = form.save(commit=False) #commit=False 允许你在保存前修改字段值。
            new_topic.owner = request.user  #将新主题的owner 属性设置为当前用户
            new_topic.save()
            
            # form.save()#调用save()，将表单中的数据写入数据库
            return redirect('learning_logs:topics')#使用 redirect()将用户的浏览器重定向到页面 topics
    
    context = {'form':form}
    return render(request,'learning_logs/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
        print("id")
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic',topic_id=topic_id)
    context = {'topic':topic,'form':form}
    return render(request,'learning_logs/new_entry.html',context)

@login_required
def edit_entry(request,entry_id):
    print("edit_entry")
    entry=Entry.objects.get(id=entry_id)
    topic=entry.topic
    
    if topic.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        form = EntryForm(instance=entry)#使用实参 instance=entry 创建一个EntryForm 实例
    else:
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic',topic_id=topic.id)
    context = {'entry':entry,'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',context)

learning_log/learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Learning Log</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
    <!-- 选择器（selector）决定了样式规则将应用于页面上的哪些元素。
     选择器 navbar-light 和 bg-light使用一种浅色来设置导航栏的背景
     mb-4 中的 mb 表示下边距。 -->
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <div class="container-fluid">
            <!-- navbar-brand 设置这个链接的样式 -->
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning_log</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <!-- 定义导航栏左侧链接的代码-->
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
                    </li>
                </ul>
                <!-- 账户相关链接 -->
                <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text me-2">Hello, {{user.username }}.
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                    </li>
                    {% endif %}
                </ul>
                <!-- 登出按钮 -->
                {% if user.is_authenticated %}
                <form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-secondary btn-sm">Log out</button>
                    {% endif %}
                </form>
            </div>
        </div>
    </nav>
    <main class="container">
        <!--<main> 元素用于定义页面
        主体的最重要的部分。这里指定了 Bootstrap 选择器
        container -->
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}
            {% endblock page_header %}

        </div>
        <div>
            {% block content %}
            {% endblock content %}
        </div>
    </main>
    <!-- <p>
        <a href="{ url 'learning_logs:index' }">Learning Log</a> -
        <a href="{ url 'learning_logs:topics' }">Topics</a> -
        is_authenticated 属性：如果用户已登录，该属性为 True，否则为 False。
        { if user.is_authenticated }
            Hello,{{user.username}}
        { else }
        <a href="{ url 'accounts:register' }">Register</a>"
        <a href="{ url 'accounts:login' }">Log in</a>
        { endif }
         learning_logs 是一个命名空间 
    </p>
    { block content }
    { endblock content }
    { if user.is_authenticated }
    <hr />
    <form action = "{ url 'accounts:logout' }" method = 'post'>
        { csrf_token }
        <button type = 'submit'>Log out</button
    </form>
    { endif } -->
</body>

</html>

learning_log/learning_logs/templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends "learning_logs/base.html" %}
    {% block content %}
    <p>
        <a href = "{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
    </p>
    <p>Edit entry:</p>
    <form action = "{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_div }}
        <button name="submit">Save changes</button>
    </form>
    {% endblock content %}
</body>
</html>

learning_log/learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}
    <!-- 子模板的第一行必须包含标签 extends，让
    Django 知道它继承了哪个父模板 -->

    {% block page_header %}
    <div class="p-3 mb-4 bg_light border rounded-3"> 
        <!-- py-4 在这个 div 中
        添加了上内边距和下内边距。 -->
        <div class ="container-fluid py-4">
            <!-- display-3 让这个标题显得更瘦更高 -->
            <h1 class="display-3">Track your learning.</h1>
            <p class="lead">Make your own Learning Log,and keep a list of the topics you're learning about.
                whenever you learn something new about a topic , make an entry summarizing what you're learned.</p>
                <!-- &raquo; 是一个 HTML 实体，表示两个右尖括号（>>） -->
                <a class="btn btn-primary btn-lg mt-1" href="{% url 'accounts:register' %}">Register &raquo;</a>
        </div>
    </div>
    {% endblock page_header %}
    {% block content %}
    <!-- 不是从父模板继承的内容都在 content块中 -->

    <!-- <p>Learning Log</p> -->
    <p>Learning Log helps you keep track of your learning,for any topic you're interested</p>
    {% endblock content %}
</body>
</html>

learning_log/learning_logs/templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends "learning_logs/base.html" %}
    {% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %} ">{{topic}}</a> </p>
    <p>Add a new entry:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_div }}
        <button name="submit">Add entry</button>
    </form>
    {% endblock content %}
</body>
</html>

learning_log/learning_logs/templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends "learning_logs/base.html" %}
    {% block content %}
    <p>Add a new topic:</p>
    <form action = "{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %}
        <!-- csrf_token来防止攻击者利用表单来对服务器进行未经授权的访问 -->
        {{ form.as_div }}
        <!-- as_div 让 Django 将所有表单元素都渲染为 HTML <div></div> -->
        <button name="submit">Add topic</button>
    </form>
    {% endblock content %}
</body>
</html>

learning_log/learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% extends "learning_logs/base.html" %}

    {% block page_header %}
    <h1>{{topic.text}}</h1>
    {% endblock page_header %}

    {% block content %}
    <p>Topic:{{topic.text}}</p>
    <p>Entries:</p>
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
    </p>
    </p>
    <ul>
        {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{entry.date_added|date:'M d, Y H:i'}}
                <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">edit_entry</a></small>
            </h4>
            <div class="card-body">{{entry.text|linebreaks}}</div>
        </div>

        
        <!-- <li> -->
            <!-- 列出时间戳需要显示属性 date_added 的值 -->
            <!-- 竖线（|）表示模板过滤器 -->
            <!-- <p>  entry.date_added|date:'M d, Y H:i'  </p> -->
            <!-- 过滤器linebreaks将包含换行符的长条目转换为浏览器能够
            理解的格式，以免显示为不间断的文本块。 -->
            <!-- <p>  entry.text|linebreaks  </p> -->
            <!-- <p> -->
                <!-- <a href=" url 'learning_logs:edit_entry' entry.id ">Edit entry</a> -->
            <!-- </p> -->
        <!-- </li> -->
        {% empty %}
        <p>There are no entries for this topic yet.</p>
        <!-- <li>There are no entries for this topic yet.</li> -->
        {% endfor %}
        {% endblock content %}
</body>

</html>

learning_log/learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% extends "learning_logs/base.html" %}

    {% block page_header %}
    <h1>Topics</h1>
    {% endblock page_header %}

    {% block content %}

    <!-- <p>Topics</p> -->

    <ul class="list-group border-bottom pb-2 mb-4">
        {% for topic in topics %}
        <li class="list-group-item border-0">
            <a href="{% url 'learning_logs:topic' topic.id %}">{{topic.text}}</a>
        </li>
        <!-- empty，它告诉 Django
        在列表 topics 为空时该怎么办。 -->
        {% empty %}
        <li class="list-group-item border-0">No topics have been added yet.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
    {% endblock content %}
</body>

</html>